### ISSUE TITLE
Clarify what <amount> represents 

### ISSUE THREAD

**Issue by themorgantown** [DeviateFish/buy-bitcoin#1]
Thanks DeviateFish :) 

When you initially type: 

`buy-bitcoin`

> Usage:
> buy-bitcoin <amount>
> buys <amount> bitcoin via GDAX 

Just a recommendation that <amount> should be clarified to designate what it represents when you type buy-bitcoin into terminal: is this in USD or BTC?

**Comment by DeviateFish** [comment]
Good call! I'll update the helptext

**Comment by DeviateFish** [comment]
@themorgantown I tweaked the language in the help text in [333105fb](https://github.com/DeviateFish/buy-bitcoin/commit/333105fbbb1befe2a826c83e7655ca49b000e78d).  Let me know if it's clear enough, or if you have a better suggestion!

**Comment by themorgantown** [comment]
Awesome, thanks!
